export type posts = {
  id: string,
  title: string,
  description: string,
  pictures: [],
  address: string,
  city: string,
  country: string,
  state: string,
  zipCode: string,
  pricePerDay: number,
  priceMonthly: number,
  needPersons: number,
  maxAge: number,
  minAge: number,
  createdBy: string,
  isActive: boolean,
  createdAt: Date,
}